

=== Pattern Factory
Le pattern factory est une solution à la duplication de code, il existe plusieurs type de pattern factory. +
Nous allons voir une solution via une énumération

==== Code original

Le bout de code de cet exemple est la creation d'un courrier avec les cas suivants :

* Une naissance
* Un mariage
* Un décès
* Autres

NOTE: Le code  n'est pas le meilleur qu'il soit, mais c'est pour l'exemple. Il faut juste imaginer de tomber sur un bout de code similaire à celui-ci répété plusieurs fois.

===== Classe de données



[%linenums,java,subs="attributes+,quotes"]
----

include::{docdir}/../../../application/src/main/java/org/document/application/pattern/factory/dto/CourrierDto.java[]
----

===== Controller
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/main/java/org/document/application/pattern/factory/controllers/CourrierController.java[]
----

===== Services

.Service Courrier dans le cas d'une naissance
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/main/java/org/document/application/pattern/factory/services/CourrierNaissanceService.java[]
----

.Service Courrier dans le cas d'un mariage
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/main/java/org/document/application/pattern/factory/services/CourrierMariageService.java[]
----

.Service Courrier dans le cas d'une décès
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/main/java/org/document/application/pattern/factory/services/CourrierDecesService.java[]
----


.Service Courrier dans le cas non connu
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/main/java/org/document/application/pattern/factory/services/CourrierAutresService.java[]
----
===== Tests unitaires
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/test/java/org/document/application/pattern/factory/controllers/CourrierControllerTest.java[]
----
==== Premier Refactoring
Souvent le premier type de réfactoring qui est fait et l'utilisation du *if* ou bien du *switch* en fonction de la version de java utilisée.
Je vais juste faire le *if*

===== Service
.Le nouveau service
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/main/java/org/document/application/pattern/factory/services/CourrierServiceWithIf.java[]
----

===== Controller
.Le nouveau Controller
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/main/java/org/document/application/pattern/factory/controllers/CourrierControllerWithIf.java[]
----

===== Tests unitaires

.Le nouveau test unitaire
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/test/java/org/document/application/pattern/factory/controllers/CourrierControllerWithIfTest.java[]
----

IMPORTANT: Le fait de mettre en place le *if*, nous oblige à mieux organiser notre code et plus qu'un seul service. Mais si d'aventure de nouveaux cas arrivaient, nous aurions un code avec une cascade de *else if*.

==== Solution Pattern Factory
Le pattern factory permet de s'affranchir des *if/else if* ou du *switch*
Pour cela, il suffit de créer une énumération

===== Enumération
.Enumération
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/main/java/org/document/application/pattern/factory/dto/CourrierFactory.java[]
----

==== Service
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/main/java/org/document/application/pattern/factory/services/CreationCourrierServiceWithEnum.java[]
----
==== Controller
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/main/java/org/document/application/pattern/factory/controllers/CourrierControllerWithEnum.java[]
----
==== Test unitaire
[%linenums,java,subs="attributes+,quotes"]
----
include::{docdir}/../../../application/src/test/java/org/document/application/pattern/factory/controllers/CourrierControllerWithEnumTest.java[]
----

